[versions]
spring-boot3 = "3.5.9"

[libraries]
# log
slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.17" }
logback = { module = "ch.qos.logback:logback-classic", version = "1.5.22" }

# jpa
jakarta-persistence-api = { module = "jakarta.persistence:jakarta.persistence-api", version = "3.2.0" }

# spring boot
spring-boot3-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring-boot3" }
spring-boot3-batch = { module = "org.springframework.boot:spring-boot-starter-batch", version.ref = "spring-boot3" }
spring-boot3-p6spy = { module = "com.github.gavlyukovskiy:p6spy-spring-boot-starter", version = "1.12.1" }
spring-boot3-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot3" }

# spring
spring-batch5-test = { module = "org.springframework.batch:spring-batch-test", version = "5.2.4" }

# hibernate
hibernate7-core = { module = "org.hibernate:hibernate-core", version = "7.2.0.Final" }

# hibernate-reactive
hibernate-reactive4-core = { module = "org.hibernate.reactive:hibernate-reactive-core", version = "4.2.0.Final" }

# eclipse-link
eclipselink4 = { module = "org.eclipse.persistence:org.eclipse.persistence.jpa", version = "4.0.8" }

# vertx
vertx-jdbc-client = { module = "io.vertx:vertx-jdbc-client", version = "5.0.6" }
vertx-jdbc-client4 = { module = "io.vertx:vertx-jdbc-client", version = "4.5.23" }
agroal-pool = { module = "io.agroal:agroal-pool", version = "2.8" }

h2 = { module = "com.h2database:h2", version = "2.4.240" }

[plugins]
spring-boot3 = { id = "org.springframework.boot", version.ref = "spring-boot3" }
