[versions]
kotlin = "1.9.0"

spring6 = "6.0.11"
spring5 = "5.3.29"

test-spring-boot3 = "3.1.3"
test-spring-boot2 = "2.7.15"

test-mutiny = "2.4.0"

[libraries]
# kotlin
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-benchmark = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime", version = "0.4.9" }

# coroutines
coroutine-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version = "1.7.3" }

# jpa
javax-persistence-api = { module = "javax.persistence:javax.persistence-api", version = "2.2" }
jakarta-persistence-api = { module = "jakarta.persistence:jakarta.persistence-api", version = "3.0.0" }

# log
slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.7" }
logback = { module = "ch.qos.logback:logback-classic", version = "1.2.11" }

# hibernate-reactive
hibernate-reactive1-core = { module = "org.hibernate.reactive:hibernate-reactive-core", version = "1.0.0.Final" }
hibernate-reactive2-core = { module = "org.hibernate.reactive:hibernate-reactive-core", version = "2.0.0.Final" }

# spring-boot
spring-boot3-starter = { module = "org.springframework.boot:spring-boot-starter", version = "3.0.3" }
spring-boot2-starter = { module = "org.springframework.boot:spring-boot-starter", version = "2.7.10" }

# spring
spring-jdbc = { module = "org.springframework:spring-jdbc", version = "6.0.11" }

spring-batch5-infrastructure = { module = "org.springframework.batch:spring-batch-infrastructure", version = "5.0.0" }
spring-batch4-infrastructure = { module = "org.springframework.batch:spring-batch-infrastructure", version = "4.0.0.RELEASE" }

# https://github.com/spring-projects/spring-data-jpa/issues/2812
spring-data-jpa3 = { module = "org.springframework.data:spring-data-jpa", version = "3.0.3" }
spring-data-jpa2 = { module = "org.springframework.data:spring-data-jpa", version = "2.7.9" }

# Eclipselink
eclipselink = { module = "org.eclipse.persistence:org.eclipse.persistence.jpa", version = "2.7.13" }
eclipselink-v4 = { module = "org.eclipse.persistence:org.eclipse.persistence.jpa", version = "4.0.2" }

# test
test-spring-boot3-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "test-spring-boot3" }
test-spring-boot3-batch = { module = "org.springframework.boot:spring-boot-starter-batch", version.ref = "test-spring-boot3" }
test-spring-boot3-p6spy = { module = "com.github.gavlyukovskiy:p6spy-spring-boot-starter", version = "1.9.0" }
test-spring-boot3-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "test-spring-boot3" }

test-spring-boot2-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "test-spring-boot2" }
test-spring-boot2-batch = { module = "org.springframework.boot:spring-boot-starter-batch", version.ref = "test-spring-boot2" }
test-spring-boot2-p6spy = { module = "com.github.gavlyukovskiy:p6spy-spring-boot-starter", version = "1.8.1" }
test-spring-boot2-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "test-spring-boot2" }

test-spring-batch5-test = { module = "org.springframework.batch:spring-batch-test", version = "5.0.3" }
test-spring-batch4-test = { module = "org.springframework.batch:spring-batch-test", version = "4.3.9" }

test-hibernate-reactive1-core = { module = "org.hibernate.reactive:hibernate-reactive-core", version = "1.1.9.Final" }
test-hibernate-reactive2-core = { module = "org.hibernate.reactive:hibernate-reactive-core", version = "2.0.5.Final" }

test-vertx-jdbc-client = { module = "io.vertx:vertx-jdbc-client", version = "4.4.5" }
test-agroal-pool = { module = "io.agroal:agroal-pool", version = "2.2" }

test-junit = { module = "org.junit.jupiter:junit-jupiter", version = "5.10.0" }
test-assertJ = { module = "org.assertj:assertj-core", version = "3.24.2" }
test-mockk = { module = "io.mockk:mockk", version = "1.13.7" }

test-h2 = { module = "com.h2database:h2", version = "2.2.222" }

[plugins]
kotlin-benchmark = { id = "org.jetbrains.kotlinx.benchmark", version = "0.4.9" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlin-noarg = { id = "org.jetbrains.kotlin.plugin.noarg", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.7.1" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.5.1" }

test-spring-boot3 = { id = "org.springframework.boot", version.ref = "test-spring-boot3" }
test-spring-boot2 = { id = "org.springframework.boot", version.ref = "test-spring-boot2" }
