[versions]
kotlin = "1.9.10"

[libraries]
# kotlin
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

# coroutines
coroutine-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version = "1.7.3" }

# jpa
javax-persistence-api = { module = "javax.persistence:javax.persistence-api", version = "2.2" }
jakarta-persistence-api = { module = "jakarta.persistence:jakarta.persistence-api", version = "3.0.0" }

# log
slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.9" }

# hibernate
hibernate5-core = { module = "org.hibernate:hibernate-core", version = "5.0.0.Final" }
hibernate6-core = { module = "org.hibernate:hibernate-core", version = "6.0.0.Final" }

# hibernate-reactive
hibernate-reactive1-core = { module = "org.hibernate.reactive:hibernate-reactive-core", version = "1.0.0.Final" }
hibernate-reactive2-core = { module = "org.hibernate.reactive:hibernate-reactive-core", version = "2.0.0.Final" }

# eclipse-link
eclipselink2 = { module = "org.eclipse.persistence:org.eclipse.persistence.jpa", version = "2.7.0" }
eclipselink3 = { module = "org.eclipse.persistence:org.eclipse.persistence.jpa", version = "3.0.0" }

# spring-boot
spring-boot3-starter = { module = "org.springframework.boot:spring-boot-starter", version = "3.0.3" }
spring-boot2-starter = { module = "org.springframework.boot:spring-boot-starter", version = "2.7.10" }

# spring
spring-jdbc = { module = "org.springframework:spring-jdbc", version = "6.0.11" }

spring-batch5-infrastructure = { module = "org.springframework.batch:spring-batch-infrastructure", version = "5.0.0" }
spring-batch4-infrastructure = { module = "org.springframework.batch:spring-batch-infrastructure", version = "4.0.0.RELEASE" }

# https://github.com/spring-projects/spring-data-jpa/issues/2812
spring-data-jpa3 = { module = "org.springframework.data:spring-data-jpa", version = "3.0.3" }
spring-data-jpa2 = { module = "org.springframework.data:spring-data-jpa", version = "2.7.9" }

# test
junit = { module = "org.junit.jupiter:junit-jupiter", version = "5.10.0" }
assertJ = { module = "org.assertj:assertj-core", version = "3.24.2" }
mockk = { module = "io.mockk:mockk", version = "1.13.7" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.7.1" }
ktlint = { id = "org.jmailen.kotlinter", version = "3.16.0" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
